### ISSUE TITLE
Collect Tutorial Requests

### ISSUE THREAD

**Issue by Cephy314** [Pantong51/GASContent#2]
I've gotten pretty familiar with the GAS at this point and would like to do some more tutorials for it on specific topics, but its such a massive broad far reaching system I think it might be good to get some input on what tutorials would be desired.  Seems like most of the tutorials out there are very broad, and more demo than tutorial without really showing how things are done.

**Comment by Pantong51** [comment]
Could do something like how to make attributes affect other attributes.

An example you have health, maxhealth, and vitality. Items in your game can grant you maxhealth or vitality.

Vitality is worth x maxhealth.


Eventually, I'm planning on helping out here as well. Still attempting to get a good grasp of the system
